# NumpPy Tuotrial
### Introduction to NumPy Arrays 
### following along from chapter 4 of 'Linear Algebra in Python' by Jason Brownlee

the main data structure in NumPy is the N-dimensional array, or ndarray. 
let's start by creating an array in a very simple way, by passing a list to the array function:

In [8]:
from numpy import array
#make a list
l = [ 1.0, 2.0, 3.0 ]
#use the array funtion to create an 'n' dimensional array object
a = array( l )
print( a )
print( a.shape )
print( a.dtype )

[1. 2. 3.]
(3,)
float64


there are other functions to create fixed size arrays:

In [9]:
#create and empty array
from numpy import empty
a = empty( [ 3,3 ] )
print( a )

[[6.92674165e-310 6.92674692e-310 6.92672910e-310]
 [6.92674474e-310 6.92672910e-310 6.37344683e-322]
 [4.63893046e-310 4.63893046e-310 6.92674587e-310]]


In [10]:
#create a zero array
from numpy import zeros
a = zeros( [ 3,5 ] )
print( a )

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#create an array of ones
from numpy import ones
a = ones( [ 5 ] )
print( a )

[1. 1. 1. 1. 1.]


combining arrays: creating new arrays from existing ones with hstack & vstack

In [12]:
from numpy import vstack
#create an array
a1 = array( [ 1,2,3 ] )
print( a1 )
#create a second array
a2 = array( [ 4,5,6 ] )
print( a2 )
#vertical stack
a3 = vstack( ( a1,a2 ) )
print( a3 )
print( a3.shape )

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
from numpy import hstack
a4 = hstack( ( a1,a2 ) )
print( a4 )
print( a4.shape )

[1 2 3 4 5 6]
(6,)


some other methods for creating arrays:

In [20]:
import numpy as np
#linspace
a5 = np.linspace( 1, 10, 19 ) 
print( a5 )

#arange
a6 = np.arange( 13 )
print( a6 )

#indeces
a7 = np.indices( ( 3,3 ) )
print( a7 )

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


another method for combining arrays:

In [23]:
#concatenate
a8 = np.concatenate((a1, a2), axis=0)
print( a8 )

[1 2 3 4 5 6]
